// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package register_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegisterServerClient is the client API for RegisterServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegisterServerClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
}

type registerServerClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterServerClient(cc grpc.ClientConnInterface) RegisterServerClient {
	return &registerServerClient{cc}
}

func (c *registerServerClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/register_server.RegisterServer/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterServerServer is the server API for RegisterServer service.
// All implementations should embed UnimplementedRegisterServerServer
// for forward compatibility
type RegisterServerServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
}

// UnimplementedRegisterServerServer should be embedded to have forward compatible implementations.
type UnimplementedRegisterServerServer struct {
}

func (UnimplementedRegisterServerServer) Register(context.Context, *RegisterRequest) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

// UnsafeRegisterServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegisterServerServer will
// result in compilation errors.
type UnsafeRegisterServerServer interface {
	mustEmbedUnimplementedRegisterServerServer()
}

func RegisterRegisterServerServer(s grpc.ServiceRegistrar, srv RegisterServerServer) {
	s.RegisterService(&RegisterServer_ServiceDesc, srv)
}

func _RegisterServer_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register_server.RegisterServer/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServerServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterServer_ServiceDesc is the grpc.ServiceDesc for RegisterServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegisterServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "register_server.RegisterServer",
	HandlerType: (*RegisterServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _RegisterServer_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "register_server.proto",
}
